export * from './global/index-page/IndexPage'
export * from './global/welcome-page/Welcome'
export * from './global/documentaion-page/DocumentationPage'
export * from './global/milancu-test/Test'
export * from './client/reservations-page/ReservationPage'